### ISSUE TITLE
osgi.enroute.rest.simple.provider - problem with workspace

### ISSUE THREAD

**Issue by dleangen** [osgi/osgi.enroute.bundles#56]
Something strange is happening with the workspace. I am no longer able to run any tests. I am wondering what has changed recently...

I needed to re-resolve the bundles, and the only change I could perceive was the update from org.apache.felix.http.jetty from version 3.1 to version 3.2.

Any ideas?

**Comment by pkriens** [comment]
Your workspace is linked to the master on the OSGi enRoute website. If you want to fix it, change the URL to the distro to v1.0.0 (see https://github.com/osgi/workspace/blob/master/cnf/ext/enroute-distro.bnd <https://github.com/osgi/workspace/blob/master/cnf/ext/enroute-distro.bnd>)

I had to update the Http because the 3.1.0 has a nasty bug.

**Comment by dleangen** [comment]
Hmmmm. If I do that, then osgi.enroute.web.simple.provider no longer compiles. :-(

**Comment by pkriens** [comment]
what error do you get?

**Comment by dleangen** [comment]
There are many. For instance:

  osgi.enroute.servlet cannot be resolved
  ServiceComponentRuntime cannot be resolved to a type

...

**Comment by pkriens** [comment]
I guess the old index did not have the ConditionalServlet? Or is there more?

But you can compile against master, after just re-resolving?

**Comment by dleangen** [comment]
Very strange. I now get errors like this:

  Project bundle [blah]/generated/osgi.enroute.rest.simple.provider.jar does not exist

And indeed, the generated directory is empty. I have restarted, refreshed, and cleaned as well as updated the repositories several times now, but no change. :-(

**Comment by pkriens** [comment]
can you commit your repo so I can take a look?

**Comment by dleangen** [comment]
It's the same repo as [PR#28](https://github.com/osgi/osgi.enroute.bundles/pull/28).

**Comment by pkriens** [comment]
Yes, v1.0.0 misses a few important parts but I can switch back and forth. Master works ok. Anyway, we need to focus on master, the failing tests all seem to be about file not found so the new Jetty seems to cause problems. We need to fix that.

I stepped through one of the failing tests and noticed that the BundleFileServer was not called while the URl started with /bnd. I changed the HTTP_WHITEBOARD_SERVLET_PATTERN to `/bnd/*` (instead of `/bnd`) and that made the tests succeed.

About the problems with Eclipse ... I sometimes have something like this. Two things you can try. Delete all the errors in the Problems view sometimes helps. Otherwise, throw away your eclipse workspace, create a new one, and import the bnd workspace.

**Comment by dleangen** [comment]
Thanks for the tips! Yes, you are right, adding "/*" to the servlet pattern does indeed work, though that doesn't seem right to me... The http service seems a bit flaky. Works sometimes, not others. Huh?

In any case, that unblocks me. Thanks a lot!!

(I'll be back at it tomorrow.)

**Comment by pkriens** [comment]
Alas, this  is the spec:
A string beginning with a ‘/’ character and ending with a ‘/*’ suffix is used for
path mapping.
■ A string beginning with a ‘*.’ prefix is used as an extension mapping.
■ The empty string ("") is a special URL pattern that exactly maps to the
application's context root, i.e., requests of the form http://host:port/<contextroot>/.
In this case the path info is ’/’ and the servlet path and context path is
empty string (““).
■ A string containing only the ’/’ character indicates the "default" servlet of the
application. In this case the servlet path is the request URI minus the context path
and the path info is null.
■ All other strings are used for exact matches only

**Comment by dleangen** [comment]
Oh! So in that case, org.apache.felix.http.jetty version 3.1 did not follow the spec, and I'll have to update my mental model (not to mention all my code). :-)

Ok, thanks!
